# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SegSam
                                 A QGIS plugin
 generate poly using SAM
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-06-26
        copyright            : (C) 2025 by Ofer Butbega
        email                : geoosamplugin@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

import os

from .import_utils import ensure_import_path


# QGIS loads this directory as the ``GeoOSAM`` package.  Meta's bundled SAM2
# code and its Hydra configuration intentionally use top-level ``sam2.*``
# imports, so make the plugin directory importable before classFactory imports
# any of the implementation modules.
PLUGIN_DIR = os.path.dirname(os.path.abspath(__file__))
ensure_import_path(PLUGIN_DIR, prepend=True)


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load SegSam class from file SegSam.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .geo_osam import SegSam
    return SegSam(iface)
